require:
  - rubocop-rspec

Naming/MethodParameterName:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

RSpec/ExampleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
